### ISSUE TITLE
Крайне неэффективное использование ресурсов.

### ISSUE THREAD

**Issue by elmurzaev** [codev01/devplus#1]
Ресурсы смартфона используются крайне неэффективно! **WebView**  инициализируется с абсолютно не используемыми предустановками. Целая гора непонятных java классов с непонятным наименованием (приставка **DPI**  - что это вообще означает, это можно было бы написать если бы речь шла о пикселях, но именовать классы..!) Твоя сборка DevPlus в целом основана на веб, в таком случае можно было бы обойтись одним Activity с функциями для работы с WebView, которые передают виджету WebView необходимые параметры, но нет же - ты разбил целую гору из Activity и в каждом из них WebView инициализируется с огромным количеством надстроек. В любой ИТ-компании тебя давно уволили бы :smile:

**Comment by elmurzaev** [comment]
И да, самое главное! На форуме ты написал что обновлений больше не будет, но возможно будет обновления программной оболочки ! И так, вопрос - а кому это оболочка нужна вообще если в ней нет контента?! Людям нужен контент а не твоя программная оболочка.

Это я образумить тебя хочу

**Comment by codev01** [comment]
@elmurzaev DevPlus я уже не разрабатываю как учебник. Он идет в качестве полигона для тестов. Обновления уроков в приложении не будут. Пользоваться приложением или нет - выбор каждого. Возможно, кому-то нужны некоторые сэмплы из кода.
